# Experimental!
~ "../lib.ua" ~ Material Mesh RenderConfig RenderMesh RenderOutput Suzanne Transform
~ "gh:Omnikar/uiua-math" ~ Qqp RQuat

RC ← RenderConfig
RO ← RenderOutput

NewLogo ← ⨬(⊙◌|◌)⧋°¤⤙⊙⊙◌˜↯0.9⊸△⧋(⊃↙↘3)Logo

NewLogo

RC⊸△₂

Suzanne

°⊸Mesh.UVs°(-⊸¬)⧋(⊂⊃↙₁↘₂)⊸Mesh.Triangles
°⊸Mesh.Materials¤Material⤸₁⇌NewLogo
∩¤
÷ ⊙+₁ ⟜⇡30
∧(
  ⟜(°⊸Mesh.Transform‥Rotation Qqp∩⌞RQuat ×τ˙×∿×π/2 ⊙(∩(÷⊸⩜⌵-⊸¬gen3) 5 1))
  ⊙(RO.GenMaterials⊸RO.GenUVs⤚RenderMesh)
  ⊂⌞⨬(◌|⊙◌)⊙⊙NewLogo⊙×⊃(⍉↯3≠∞⋅RO.Index|⋅RO.Material‥Albedo|↧1+¬⊙RO.Light)
)
⊂⟜⇌⊂˙⊟NewLogo⇌
&gifs 15
